### ISSUE TITLE
I want to build nuclear reactors on all provinces.

### ISSUE THREAD

**Issue by kotenok2000** [CalamariAce/hoiiiicheats#3]

**Comment by CalamariAce** [comment]
Sorry there's not a great way to do that right now, but you could do the following:
1. Manually add one reactor to the production queue for each province, then save and quit the game
2. Run military_construction.py to set full progress on everything in your build queue
3. Run the game until the first reactors have been placed in each province.
4. If more reactors are wanted, save and quit the game again, then run nuclear_reactor.py to increase the reactor count in each province (to 10, for example).

I just added the script for nuclear_reactor.py, so pull the latest code if you are missing it.
